# Matrizes

In [53]:
import numpy as np

In [ ]:
matriz = np.array([[2, 3, 1], 
                   [4, 5, 7]])

In [ ]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [ ]:
matriz.shape

(2, 3)

In [ ]:
matriz[0]

array([2, 3, 1])

In [ ]:
matriz[1]

array([4, 5, 7])

In [ ]:
matriz[0][2]

1

In [ ]:
matriz[1][2]

7

In [ ]:
matriz.shape

(2, 3)

In [ ]:
for i in range(matriz.shape[0]):
  print(matriz[i])
  for j in range(matriz.shape[1]):
    print(matriz[i][j])  

[2 3 1]
2
3
1
[4 5 7]
4
5
7


EXERCÍCIOS

In [24]:
#EXERCÍCIO 1
lista = []
for i in range(1, 6):
  lista.append(int(input("Digite o numero: ")))

numero = 0;
soma = 0;
while numero <=4:
  soma += lista[numero]
  numero+=1

print("Soma:", soma)


Digite o numero: 10
Digite o numero: 20
Digite o numero: 30
Digite o numero: 40
Digite o numero: 50
Soma:  150


In [51]:
#EXERCÍCIO 2
dicionario = {}
nota = 0
for i in range(0,3):
  nome = input('Digite o nome: ')
  nota = int(input("Digite a nota: "))
  dicionario[nome] = nota

soma = 0;
for nomes, notas in dicionario.items():
  print(notas)
  soma += notas;


media = soma/3
print(media)


Digite o nome: a
Digite a nota: 1
Digite o nome: b
Digite a nota: 2
Digite o nome: c
Digite a nota: 3
1
2
3
2.0


In [55]:
#EXERCÍCIO 3
matriz = np.array([[2, 3, 1], 
                   [4, 5, 7]])

soma = 0;

for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    print(matriz[i][j])  ##Percorre cada elemento
    soma += matriz[i][j]
print(soma)


2
3
1
4
5
7
